### Creates a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "laddu",
  "email": "laddu@email.com",
  "address": "jiyaguda",
  "dateOfBirth": "2007-02-01",
  "registerDate": "2025-02-12"
}

###